#!/bin/sh
alias g='git'
alias ga='git add'
alias gau='git add -u'
alias gb='git branch'
alias gba='git branch -a'
alias gcamend='git commit --amend --no-edit'
alias gco='git checkout'
alias gcom='git commit'
alias gcomm='git commit -m'
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git log --decorate --oneline'
alias gg='git log --oneline --graph --decorate'
alias ggb='git log --oneline --graph --decorate --branches --all'
alias gr='git reflog --date=relative'
alias grc='git rebase --continue'
alias gri='git rebase -i'
alias groot='cd "$(git rev-parse --show-toplevel)" ; echo "I am Groot"'
alias gs='git status'
