#!/bin/sh
alias g10='git log -n 10'
alias g='git'
alias ga='git add'
alias gau='git add -u'
alias gb='git branch'
alias gba='git branch -a'
alias gbr='git branch -r'
alias gbdev='git branch -a | grep -i develop'
alias gcamend='git commit --amend --no-edit --date=now'
alias gco='git checkout'
alias gcom='git commit'
alias gcomm='git commit -m'
alias gd='git diff'
alias gds='git diff --staged'
alias gdu='git diff @{upstream}'
alias gg='git log --oneline --graph --decorate'
alias ggb='git log --graph --decorate --branches --all'
alias gl='git log --decorate --oneline'
alias glu='git log --decorate --oneline @{upstream}'..
alias gr='git reflog --date=relative'
alias grc='git rebase --continue'
alias gri='git rebase -i --autostash --autosquash'
alias groot='cd "$(git rev-parse --show-toplevel)" ; echo "I am Groot"'
alias grrr='git rebase'
alias gru='git remote update'
alias grup='git remote update -p'
alias gs='git status'
