set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=l
set guioptions-=R
set guioptions-=L
set guioptions+=c
set guicursor=a:blinkon0
let g:solarized_italic=0
colo solarized
set bg=light
set mousehide
set mousefocus
set cursorline
set linespace=0
set guiheadroom=0
set lines=30
set columns=80
highlight Cursor guifg=black guibg=red
