* Swiper
** Send bm toggle keys through to main buffer
** Use active selection as initial search
* Random buggy stuff noticed
** Cucumber mode indent
Electric indent on enter for a "Given" indents to the wrong place?
Turns out Cucumber mode disables it! PR to fix?
** Compile mode recentre while in follow-mode seems broken
** Creating a bad process with make-process (missing args?) seems to break everything.
** Highlights in log are bad
If I set a bunch of highlights and then scroll far away, the strings
are no longer highlighted. It's as-if it only works for a small
portion of the buffer.
** Duplicate thing doesn't work if there is no newline
* Ideas
** Mega-highlight mode
Eval the contents of a buffer to get a set of highlight strings and
highlight them all in visible buffers. Do it automatically after a
timeout.
** Read-only if not in VCS
** Smarter function help
When I press <f1> I get help on the current function. But I still have
to press <enter> as well. It would be nice if an exact match at point
would just bring up the function immediately.
