syntax on
filetype on
map Y y$
" imap <CR> <ESC> 
nmap <silent> <Down> :wincmd j<CR>
nmap <silent> <Left> :wincmd h<CR>
nmap <silent> <Right> :wincmd l<CR>
nmap <silent> <Up> :wincmd k<CR>
nmap <silent> <C-Up> :prev<CR>
nmap <silent> <C-Down> :next<CR>
nore , ;
nore ; :
nore <leader>h :set hls!<CR>
nore <leader>w :%s/\s\+$//ge<CR>
nore gf gF
set autoindent
set backspace=indent,eol,start
set clipboard=unnamed
set expandtab
set fillchars+=vert:\ 
set ignorecase
set isfname-=:
set linebreak
set mouse=a
set nocp
set nojoinspaces
set nowrap
set nowrapscan
set number
set ruler
set shiftwidth=2
set shortmess=aoOtI
set smartcase
set softtabstop=2
set tabstop=4
set tw=0
set virtualedit+=block
set incsearch
set fo-=o
set hidden
set path+=**
set relativenumber

" If a swap file exists, just open in read-only mode automatically.
" autocmd SwapExists * let v:swapchoice = "o"

autocmd BufNewFile,BufRead Jenkinsfile set syntax=groovy

set completeopt=longest
set wildmode=list:longest
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.o,*~,*.hi

noremap Q <Nop>

inoremap <f12> <ESC>
noremap <f12> :w<CR>

let netrw_banner=0
